//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDangNhap
    {
        public int idDangNhap { get; set; }
        public int maTaiKhoan { get; set; }
        public System.DateTime tgDangNhap { get; set; }
        public Nullable<System.DateTime> tgDangXuat { get; set; }
    }
}
