//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiet_Quyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chitiet_Quyen()
        {
            this.ChiTietQuyen_Quyen = new HashSet<ChiTietQuyen_Quyen>();
        }
    
        public string maChitietQuyen { get; set; }
        public string tenhanhDong { get; set; }
        public string mahanhDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietQuyen_Quyen> ChiTietQuyen_Quyen { get; set; }
    }
}
