//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChamCong = new HashSet<ChamCong>();
            this.ChuyenCongTac_NhanVien = new HashSet<ChuyenCongTac_NhanVien>();
        }
    
        public string maNhanVien { get; set; }
        public string tenNhanVien { get; set; }
        public string gioiTinh { get; set; }
        public System.DateTime ngaySinh { get; set; }
        public string CCCD { get; set; }
        public string dienThoai { get; set; }
        public string noiOHienTai { get; set; }
        public string queQuan { get; set; }
        public Nullable<int> maHoSo { get; set; }
        public int maTrinhDo { get; set; }
        public int maTonGiao { get; set; }
        public int maChuyenMon { get; set; }
        public int maDanToc { get; set; }
        public int maChucVu { get; set; }
        public Nullable<int> maHopDong { get; set; }
        public int maPhong { get; set; }
        public string anhThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamCong> ChamCong { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenCongTac_NhanVien> ChuyenCongTac_NhanVien { get; set; }
        public virtual ChuyenMon ChuyenMon { get; set; }
        public virtual DanToc DanToc { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TonGiao TonGiao { get; set; }
        public virtual TrinhDo TrinhDo { get; set; }
    }
}
