//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int maTaiKhoan { get; set; }
        public string tenTaiKhoan { get; set; }
        public string matKhau { get; set; }
        public string maQuyen { get; set; }
        public bool trangThai { get; set; }
    
        public virtual Quyen Quyen { get; set; }
    }
}
