//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenCongTac_NhanVien
    {
        public string soQuyetDinh { get; set; }
        public string maNhanVien { get; set; }
        public Nullable<int> chucVuCu { get; set; }
        public Nullable<int> phongBanCu { get; set; }
        public Nullable<int> chucVuMoi { get; set; }
        public Nullable<int> phongBanMoi { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual ChuyenCongTac ChuyenCongTac { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
