//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int maHopDong { get; set; }
        public string soHopDong { get; set; }
        public Nullable<System.DateTime> ngayKyHD { get; set; }
        public Nullable<System.DateTime> ngayKetThucHD { get; set; }
        public string loaiHopDong { get; set; }
        public string thoiHanHD { get; set; }
        public string tinhTrangChuKi { get; set; }
    }
}
